# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git cmake libalglib-dev libnlopt-cxx-dev libeigen3-dev libboost-filesystem-dev libboost-log-dev libgsl-dev numdiff
    - name: Restore PhaseTracer
      continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        path: /home/runner/.TransitionSolver
        key: ${{ runner.os }}_phase_tracer
    - name: Install TransitionFinder
      run: |
        sudo apt install git cmake libalglib-dev libnlopt-cxx-dev libeigen3-dev libboost-filesystem-dev libboost-log-dev libgsl-dev numdiff
        python -m pip install --upgrade pip
        pip install .
    - name: Save PhaseTracer
      uses: actions/cache/save@v4
      with:
        path: /home/runner/.TransitionSolver
        key: ${{ runner.os }}_phase_tracer
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install .[test]
        pytest
    - name: Try CLI
      run: |
        ts --model RSS_BP --point input/RSS/RSS_BP1.txt
    - name: Install script test dependencies
      run: |
        mkdir -p config
        echo '{ "PhaseTracer_directory": "/home/runner/.PhaseTracer/" }' > config/config_user.json
        sudo apt install numdiff
    - name: Test script output
      continue-on-error: true
      run: |
        python3 -m examples.command_line_interface rss 1 script_output input/RSS/RSS_BP3.txt
        sed -i '/^\s*"analysisTime"/d' tests/RSS_BP35ab2907aa2a62d9b479c42c639658bf8ef5b197f/phase_history.json script_output/phase_history.json
        numdiff tests/RSS_BP35ab2907aa2a62d9b479c42c639658bf8ef5b197f/phase_history.json script_output/phase_history.json
        numdiff tests/RSS_BP35ab2907aa2a62d9b479c42c639658bf8ef5b197f/phase_structure.dat script_output/phase_structure.dat
    - name: Test more complicated phase history script output
      continue-on-error: true
      run: |
        mkdir -p RSS_new_BP4_output
        python3 -m examples.command_line_interface rss 1 RSS_new_BP4_output input/RSS/RSS_new_BP4.txt
        sed -i '/^\s*"analysisTime"/d' tests/RSS_new_BP4_23_12_2025/phase_history.json RSS_new_BP4_output/phase_history.json
        numdiff tests/RSS_new_BP4_23_12_2025/phase_history.json RSS_new_BP4_output/phase_history.json
        numdiff tests/RSS_new_BP4_23_12_2025/phase_structure.dat RSS_new_BP4_output/phase_structure.dat
    - name: Test pipeline example output
      continue-on-error: true
      run: |
        mkdir -p output/pipeline_example_output
        python3 -m examples.pipeline_example
        sed -i '/^\s*"analysisTime"/d' tests/pipeline_example30_12_2025/phase_history.json output/pipeline_example_output/phase_history.json
        numdiff tests/pipeline_example30_12_2025/phase_history.json output/pipeline_example_output/phase_history.json
        numdiff tests/pipeline_example30_12_2025/phase_structure.dat output/pipeline_example_output/phase_structure.dat
